import { StyleSheet } from "react-native";
import { colors, spacing, dimensions } from "../theme";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  editButton: {
    position: "absolute",
    bottom: spacing.md,
    right: spacing.md,
    margin: spacing.sm,
  },
  uploadedImage: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: dimensions.screenWidth * 0.25,
    height: dimensions.screenWidth * 0.25,
    marginTop: -(dimensions.screenWidth * 0.25) / 2,
    marginLeft: -(dimensions.screenWidth * 0.25) / 2,
  },

  // backgroundMode: {
  //   flex: 1,
  //   alignItems: "center",
  //   justifyContent: "center",
  //   padding: spacing.md,
  //   backgroundColor: "#000000",
  // },
  // filmStripMode: {
  //   flex: 1,
  //   backgroundColor: "#1a1a1a",
  //   position: "relative",
  // },
  // filmStripContainer: {
  //   flex: 1,
  //   backgroundColor: "#2a2a2a",
  //   marginHorizontal: spacing.lg,
  //   marginVertical: spacing.xl,
  //   borderRadius: 12,
  //   overflow: "hidden",
  //   position: "relative",
  // },
  // filmHoles: {
  //   position: "absolute",
  //   left: 0,
  //   top: 0,
  //   bottom: 0,
  //   width: 20,
  //   backgroundColor: "#1a1a1a",
  //   zIndex: 2,
  // },
  // filmHolesRight: {
  //   position: "absolute",
  //   right: 0,
  //   top: 0,
  //   bottom: 0,
  //   width: 20,
  //   backgroundColor: "#1a1a1a",
  //   zIndex: 2,
  // },
  // filmHole: {
  //   width: 8,
  //   height: 12,
  //   backgroundColor: "#000000",
  //   marginLeft: 6,
  //   marginVertical: 8,
  //   borderRadius: 2,
  // },
  // filmContent: {
  //   flex: 1,
  //   backgroundColor: "#f5f5f5",
  //   marginHorizontal: 20,
  //   alignItems: "center",
  //   justifyContent: "center",
  //   padding: spacing.lg,
  // },
  // modeToggle: {
  //   position: "absolute",
  //   bottom: 20,
  //   right: 20,
  //   backgroundColor: colors.primary,
  //   paddingHorizontal: spacing.md,
  //   paddingVertical: spacing.sm,
  //   borderRadius: 20,
  //   zIndex: 10,
  // },
  // modeToggleText: {
  //   color: colors.background,
  //   fontWeight: "600",
  //   fontSize: 12,
  // },
  // lightText: {
  //   color: "#FFFFFF",
  // },
  // filmStripBorder: {
  //   position: "absolute",
  //   top: 0,
  //   left: 20,
  //   right: 20,
  //   height: 2,
  //   backgroundColor: "#000000",
  // },
  // filmStripBorderBottom: {
  //   position: "absolute",
  //   bottom: 0,
  //   left: 20,
  //   right: 20,
  //   height: 2,
  //   backgroundColor: "#000000",
  // },
});
